INSERT INTO courses VALUES (DEFAULT, 'DEU', 'Deutsch');
INSERT INTO courses VALUES (DEFAULT, 'ITA', 'ITA');
INSERT INTO courses VALUES (DEFAULT, 'ENG', 'ENG');
INSERT INTO courses VALUES (DEFAULT, 'FRA', 'FRA');
INSERT INTO courses VALUES (DEFAULT, 'LAT', 'LAT');
INSERT INTO courses VALUES (DEFAULT, 'KUN', 'KUN');
INSERT INTO courses VALUES (DEFAULT, 'MUS', 'MUS');